# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-devops-project-service
spec:
  selector:
    app: my-devops-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

